#!/usr/bin/env bash 

source ~/.profile ~/.env ~/.zshenv

ARCH=""
SEPARATOR='\n====================================\n'
case $(uname -m) in
  i386 | i686)   ARCH="386" ;;
  x86_64) ARCH="amd64" ;;
  arm)    dpkg --print-architecture | grep -q "arm64" && ARCH="arm64" || architecture="arm" ;;
esac

echo -e $SEPARATOR

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

pkgs="stow, zsh, fzf, tmux, ripgrep, neovim, go, xdg-desktop-portal, hyprpolkitagent, less, ttf-jetbrains-mono-nerd, yad"
echo "Installing $pkgs"
sudo pacman -S --needed --noconfirm $(echo $pkgs | sed "s/, / /g")
 
echo -e $SEPARATOR

pushd $DOTFILES
STOW_FOLDERS="scripts,tmux,nvim,zsh,hypr,kitty,fonts,ghostty"
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do 
    echo "stow $folder"
    stow -R $folder
done

echo -e $SEPARATOR

echo "Pulling git submodules"
git submodule update --init --recursive >/dev/null 

echo -e $SEPARATOR
if ! command -v rustup &> /dev/null; then
  echo "Installing Rust"
  sudo pacman -S --needed --noconfirm rustup
  rustup default stable
else
  echo "Rust already installed $(rustc -V)"
fi

echo -e $SEPARATOR

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if ! command -v nvm &> /dev/null; then
  echo "Installing NodeJs (NVM)"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash 
else 
  echo "NVM already installed $(nvm -v)"
fi

if (! command -v npm &> /dev/null) && (command -v nvm &> /dev/null); then
  nvm install --lts
else
  echo "npm already installed"
fi

echo -e $SEPARATOR

p10k_folder="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
if [[ ! -d $p10k_folder ]]; then
  echo "Cloning powerlevel10k omz theme"
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$p10k_folder" >/dev/null
else
  echo "powerlevel10k theme already exists"
fi

echo -e $SEPARATOR

echo "Caching fonts"
fc-cache -f "$HOME/.fonts"

echo -e $SEPARATOR

if [[ "$SHELL" != *"zsh" ]]; then
  echo "Setting zsh as default shell"
  chsh $USER -s $(which zsh)
else
  echo "zsh already default shell"
fi

echo -e $SEPARATOR

source ~/.profile ~/.env ~/.zshenv

echo "Done."

popd
